name: Duplicate Issue Search

on:
  issues:
    types:
      - opened

permissions:
  issues: write
  models: read
  contents: read

jobs:
  prepare-batches:
    runs-on: ubuntu-latest
    outputs:
      batch_matrix: ${{ steps.batch-script.outputs.batch_matrix }}
      total_batches: ${{ steps.batch-script.outputs.total_batches }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Fetch and process issues in batches
        id: batch-script
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NEW_ISSUE_TITLE: ${{ github.event.issue.title }}
          NEW_ISSUE_BODY: ${{ github.event.issue.body }}
          NEW_ISSUE_NUMBER: ${{ github.event.issue.number }}
          REPO: ${{ github.repository }}
          TIME_FILTER: '1 year ago'
          BATCH_SIZE: 50
          MODEL_NAME: openai/gpt-4.1
          MAX_TOKENS: 2000
        run: ./.github/scripts/duplicate_issue_search.sh
